/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voucher1.pkg0;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cheeseball
 */
public class ADMINEDIT extends javax.swing.JFrame {
int switch1;
int switch2;
    /**
     * Creates new form ADMINEDIT
     */
    public ADMINEDIT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        adminEditUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminEditPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adminEditLastName = new javax.swing.JTextField();
        adminEditFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adminEditMiddleName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adminEditTrack = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        adminEditPreviousSchool = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        adminEditYear = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        adminStudentId = new javax.swing.JTextField();
        adminEditSchoolTypePrivate = new javax.swing.JRadioButton();
        adminEditSchoolTypePublic = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        adminEditVoucher1 = new javax.swing.JRadioButton();
        adminEditVoucher2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        adminEditGradeLevel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1461, 530));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("SAVE CHANGES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        adminEditUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("USERNAME:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("PASSWORD:");

        adminEditPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("LAST NAME:");

        adminEditLastName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        adminEditFirstName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("FIRST NAME:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("MIDDLE NAME:");

        adminEditMiddleName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("TRACK/STRAND:");

        adminEditTrack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminEditTrack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABM", "HUMMS", "ICT", "STEM" }));
        adminEditTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditTrackActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("LAST SCHOOL ATTENDED:");

        adminEditPreviousSchool.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("YEAR GRADUATED:");

        adminEditYear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminEditYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("SCHOOL TYPE:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("VOUCHER STATUS:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("ACCOUNT ID:");

        adminStudentId.setEditable(false);
        adminStudentId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        buttonGroup1.add(adminEditSchoolTypePrivate);
        adminEditSchoolTypePrivate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminEditSchoolTypePrivate.setText("PRIVATE");
        adminEditSchoolTypePrivate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminEditSchoolTypePrivateMouseClicked(evt);
            }
        });

        buttonGroup1.add(adminEditSchoolTypePublic);
        adminEditSchoolTypePublic.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminEditSchoolTypePublic.setText("PUBLIC");
        adminEditSchoolTypePublic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminEditSchoolTypePublicMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminEditSchoolTypePublicMouseReleased(evt);
            }
        });
        adminEditSchoolTypePublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditSchoolTypePublicActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("ADMIN EDIT STUDENT ACCOUNT PAGE");

        buttonGroup2.add(adminEditVoucher1);
        adminEditVoucher1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminEditVoucher1.setText("NON-ESC GUARANTEE");
        adminEditVoucher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditVoucher1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(adminEditVoucher2);
        adminEditVoucher2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminEditVoucher2.setText("ESC GUARANTEE");
        adminEditVoucher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditVoucher2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("GO BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("GRADE LEVEL:");

        adminEditGradeLevel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adminEditGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRADE 11", "GRADE 12" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminEditSchoolTypePrivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminEditSchoolTypePublic)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminEditPreviousSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminEditYear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adminEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adminEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adminEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adminEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminEditMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminEditGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminEditTrack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminEditVoucher1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminEditVoucher2)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditSchoolTypePrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditSchoolTypePublic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditPreviousSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditGradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditVoucher1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditVoucher2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminEditTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditTrackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEditTrackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String gradeLevel = adminEditGradeLevel.getSelectedItem().toString();
        int result = JOptionPane.showConfirmDialog(null, "Discard changes?", "UNSAVED PROGRESS", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            switch (gradeLevel) {
                case "GRADE 11":
                    dispose();
                    ADMINFORM grade11 = new ADMINFORM();
                    grade11.setVisible(true);
                    break;
                case "GRADE 12":
                    dispose();
                    ADMINFORM2 grade12 = new ADMINFORM2();
                    grade12.setVisible(true);
                    break;
                default:
                    dispose();
                    ADMINHUB hub = new ADMINHUB();
                    hub.setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adminEditSchoolTypePublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditSchoolTypePublicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEditSchoolTypePublicActionPerformed

    private void adminEditSchoolTypePublicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminEditSchoolTypePublicMouseClicked
    adminEditSchoolTypePublic.addActionListener(e -> {
            if (adminEditSchoolTypePublic.isSelected()){
                adminEditVoucher1.setText("NOT VOUCHER RECIPIENT");
                adminEditVoucher2.setText("VOUCHER RECIPIENT");
            }
});
    }//GEN-LAST:event_adminEditSchoolTypePublicMouseClicked

    private void adminEditSchoolTypePublicMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminEditSchoolTypePublicMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEditSchoolTypePublicMouseReleased

    private void adminEditSchoolTypePrivateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminEditSchoolTypePrivateMouseClicked
    adminEditSchoolTypePrivate.addActionListener(e -> {
            if (adminEditSchoolTypePrivate.isSelected()){
                adminEditVoucher1.setText("NON-ESC GUARANTEE");
                adminEditVoucher2.setText("ESC GUARANTEE");
            }
});
    }//GEN-LAST:event_adminEditSchoolTypePrivateMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String strandType = adminEditTrack.getSelectedItem().toString();
        String yearGraduated = adminEditYear.getSelectedItem().toString();
        String gradeLevel = adminEditGradeLevel.getSelectedItem().toString();
    if (adminEditUsername.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter a username","Missing Information", JOptionPane.INFORMATION_MESSAGE);
    } else if (adminEditPassword.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter a password","Missing Information", JOptionPane.INFORMATION_MESSAGE);
    } else if (adminEditLastName.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter a last name","Missing Information", JOptionPane.INFORMATION_MESSAGE);
    } else if (adminEditFirstName.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter your first name","Missing Information", JOptionPane.INFORMATION_MESSAGE);   
    } else if (adminEditMiddleName.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter your middle name","Missing Information", JOptionPane.INFORMATION_MESSAGE);
    } else if (adminEditPreviousSchool.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter your last school attended","Missing Information", JOptionPane.INFORMATION_MESSAGE);
    } else {
    int response = JOptionPane.showConfirmDialog(null, "Save changes?", "CONFIRMATION", JOptionPane.YES_NO_OPTION);
    if (response == JOptionPane.YES_OPTION) 
    {
        if (adminEditSchoolTypePrivate.isSelected() == true) { // PRIVATE
                switch(switch1) { 
                        case 1: // NON-ESC
                                    try {
                                    Class.forName("com.mysql.cj.jdbc.Driver");
                                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/accounts","root","");
                                    Statement st = con.createStatement();
                                    String username = adminEditUsername.getText();
                                    String usernameToEdit = adminEditUsername.getText();
                                    String password = adminEditPassword.getText();
                                    String lastname = adminEditLastName.getText();
                                    String firstname = adminEditFirstName.getText();
                                    String middlename = adminEditMiddleName.getText();
                                    String schooltype = adminEditSchoolTypePrivate.getText();
                                    String voucherstatus = adminEditVoucher1.getText();
                                    String previousschool = adminEditPreviousSchool.getText();
                                    String sql = "UPDATE user SET username = '"+usernameToEdit+"', password = '"+password+"', lastname = '"+lastname+"', firstname = '"+firstname+"', middlename = '"+middlename+"',trackstand ='"+strandType+"',schooltype ='"+schooltype+"',voucherstatus ='"+voucherstatus+"',previousschool ='"+previousschool+"',yeargraduated ='"+yearGraduated+"',gradelevel ='"+gradeLevel+"' WHERE username = '"+username+"';";
                                    int i = st.executeUpdate(sql);
                                    if (i > 0) {
                                        JOptionPane.showMessageDialog(null, "Saved changes","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                                    switch (gradeLevel) {
                                    case "GRADE 11":
                                        dispose();
                                        ADMINFORM grade11 = new ADMINFORM();
                                        grade11.setVisible(true);
                                        break;
                                    case "GRADE 12":
                                        dispose();
                                        ADMINFORM2 grade12 = new ADMINFORM2();
                                        grade12.setVisible(true);
                                        break;
                                    default:
                                        dispose();
                                        ADMINHUB hub = new ADMINHUB();
                                        hub.setVisible(true);
                                        break;
                                    }  
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Unable to save changes","FAILED",JOptionPane.INFORMATION_MESSAGE);
                                    }
                                    con.close();
                                    } catch(Exception e){
                                        System.out.println(e);
                                    }
                                    break;
                        case 2: // ESC
                                    try {
                                    Class.forName("com.mysql.cj.jdbc.Driver");
                                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/accounts","root","");
                                    Statement st = con.createStatement();
                                    String username = adminEditUsername.getText();
                                    String usernameToEdit = adminEditUsername.getText();
                                    String password = adminEditPassword.getText();
                                    String lastname = adminEditLastName.getText();
                                    String firstname = adminEditFirstName.getText();
                                    String middlename = adminEditMiddleName.getText();
                                    String schooltype = adminEditSchoolTypePrivate.getText();
                                    String voucherstatus = adminEditVoucher2.getText();
                                    String previousschool = adminEditPreviousSchool.getText();
                                    String sql = "UPDATE user SET username = '"+usernameToEdit+"', password = '"+password+"', lastname = '"+lastname+"', firstname = '"+firstname+"', middlename = '"+middlename+"',trackstand ='"+strandType+"',schooltype ='"+schooltype+"',voucherstatus ='"+voucherstatus+"',previousschool ='"+previousschool+"',yeargraduated ='"+yearGraduated+"',gradelevel ='"+gradeLevel+"' WHERE username = '"+username+"';";
                                    int i = st.executeUpdate(sql);
                                    if (i > 0) {
                                        JOptionPane.showMessageDialog(null, "Saved changes","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                                    switch (gradeLevel) {
                                    case "GRADE 11":
                                        dispose();
                                        ADMINFORM grade11 = new ADMINFORM();
                                        grade11.setVisible(true);
                                        break;
                                    case "GRADE 12":
                                        dispose();
                                        ADMINFORM2 grade12 = new ADMINFORM2();
                                        grade12.setVisible(true);
                                        break;
                                    default:
                                        dispose();
                                        ADMINHUB hub = new ADMINHUB();
                                        hub.setVisible(true);
                                        break;
                                    }  
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Unable to save changes","FAILED",JOptionPane.INFORMATION_MESSAGE);
                                    }
                                    con.close();
                                    } catch(Exception e){
                                        System.out.println(e);
                                    }
                                    break;
                        default:
                                JOptionPane.showMessageDialog(this, "Please select a voucher type", "MISSING INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                            
                    }
                }
                else if (adminEditSchoolTypePublic.isSelected() == true ) // PUBLIC
                {
                    switch (switch1) { // NON-ESC
                        case 1:
                                    try {
                                    Class.forName("com.mysql.cj.jdbc.Driver");
                                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/accounts","root","");
                                    Statement st = con.createStatement();
                                    String username = adminEditUsername.getText();
                                    String usernameToEdit = adminEditUsername.getText();
                                    String password = adminEditPassword.getText();
                                    String lastname = adminEditLastName.getText();
                                    String firstname = adminEditFirstName.getText();
                                    String middlename = adminEditMiddleName.getText();
                                    String schooltype = adminEditSchoolTypePublic.getText();
                                    String voucherstatus = adminEditVoucher1.getText();
                                    String previousschool = adminEditPreviousSchool.getText();
                                    String sql = "UPDATE user SET username = '"+usernameToEdit+"', password = '"+password+"', lastname = '"+lastname+"', firstname = '"+firstname+"', middlename = '"+middlename+"',trackstand ='"+strandType+"',schooltype ='"+schooltype+"',voucherstatus ='"+voucherstatus+"',previousschool ='"+previousschool+"',yeargraduated ='"+yearGraduated+"',gradelevel ='"+gradeLevel+"' WHERE username = '"+username+"';";
                                    int i = st.executeUpdate(sql);
                                    if (i > 0) {
                                        JOptionPane.showMessageDialog(null, "Saved changes","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                                    switch (gradeLevel) {
                                    case "GRADE 11":
                                        dispose();
                                        ADMINFORM grade11 = new ADMINFORM();
                                        grade11.setVisible(true);
                                        break;
                                    case "GRADE 12":
                                        dispose();
                                        ADMINFORM2 grade12 = new ADMINFORM2();
                                        grade12.setVisible(true);
                                        break;
                                    default:
                                        dispose();
                                        ADMINHUB hub = new ADMINHUB();
                                        hub.setVisible(true);
                                        break;
                                    }  
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Unable to save changes","FAILED",JOptionPane.INFORMATION_MESSAGE);
                                    }
                                    con.close();
                                    } catch(Exception e){
                                        System.out.println(e);
                                    }
                                    break;
                        case 2 : //ESC
                                    try {
                                    Class.forName("com.mysql.cj.jdbc.Driver");
                                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/accounts","root","");
                                    Statement st = con.createStatement();
                                    String username = adminEditUsername.getText();
                                    String usernameToEdit = adminEditUsername.getText();
                                    String password = adminEditPassword.getText();
                                    String lastname = adminEditLastName.getText();
                                    String firstname = adminEditFirstName.getText();
                                    String middlename = adminEditMiddleName.getText();
                                    String schooltype = adminEditSchoolTypePublic.getText();
                                    String voucherstatus = adminEditVoucher2.getText();
                                    String previousschool = adminEditPreviousSchool.getText();
                                    String sql = "UPDATE user SET username = '"+usernameToEdit+"', password = '"+password+"', lastname = '"+lastname+"', firstname = '"+firstname+"', middlename = '"+middlename+"',trackstand ='"+strandType+"',schooltype ='"+schooltype+"',voucherstatus ='"+voucherstatus+"',previousschool ='"+previousschool+"',yeargraduated ='"+yearGraduated+"',gradelevel ='"+gradeLevel+"' WHERE username = '"+username+"';";
                                    int i = st.executeUpdate(sql);
                                    if (i > 0) {
                                        JOptionPane.showMessageDialog(null, "Saved changes","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                                    switch (gradeLevel) {
                                    case "GRADE 11":
                                        dispose();
                                        ADMINFORM grade11 = new ADMINFORM();
                                        grade11.setVisible(true);
                                        break;
                                    case "GRADE 12":
                                        dispose();
                                        ADMINFORM2 grade12 = new ADMINFORM2();
                                        grade12.setVisible(true);
                                        break;
                                    default:
                                        dispose();
                                        ADMINHUB hub = new ADMINHUB();
                                        hub.setVisible(true);
                                        break;
                                    }      
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Unable to save changes","FAILED",JOptionPane.INFORMATION_MESSAGE);
                                    }
                                    con.close();
                                    } catch(Exception e){
                                        System.out.println(e);
                                    }
                                    break;
                        default:
                                JOptionPane.showMessageDialog(this, "Please select a voucher type", "MISSING INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Please select a school type","Missing Information", JOptionPane.INFORMATION_MESSAGE);
                }

        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adminEditVoucher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditVoucher1ActionPerformed
    switch1 = 1;
    }//GEN-LAST:event_adminEditVoucher1ActionPerformed

    private void adminEditVoucher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditVoucher2ActionPerformed
    switch1 = 2;
    }//GEN-LAST:event_adminEditVoucher2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMINEDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMINEDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMINEDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMINEDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMINEDIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField adminEditFirstName;
    public javax.swing.JComboBox<String> adminEditGradeLevel;
    public javax.swing.JTextField adminEditLastName;
    public javax.swing.JTextField adminEditMiddleName;
    public javax.swing.JTextField adminEditPassword;
    public javax.swing.JTextField adminEditPreviousSchool;
    public javax.swing.JRadioButton adminEditSchoolTypePrivate;
    public javax.swing.JRadioButton adminEditSchoolTypePublic;
    public javax.swing.JComboBox<String> adminEditTrack;
    public javax.swing.JTextField adminEditUsername;
    public javax.swing.JRadioButton adminEditVoucher1;
    public javax.swing.JRadioButton adminEditVoucher2;
    public javax.swing.JComboBox<String> adminEditYear;
    public javax.swing.JTextField adminStudentId;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
