/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package voucher1.pkg0;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Cheeseball
 */
public class ADMINFORM2 extends javax.swing.JFrame {

    /**
     * Creates new form ADMINFORM2
     */
    public ADMINFORM2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1087, 676));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("TO GRADE 11 DATABASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("TO ADMIN PANEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ACCOUNT DATABASE GRADE 12");

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "USERNAME", "PASSWORD", "LAST NAME", "FIRST NAME", "TRACK/STRAND", "SCHOOL TYPE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("SEARCH BAR:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("UPDATE TABLE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("VIEW ACCOUNT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setText("DELETE ACCOUNT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(84, 84, 84)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 174, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        ADMINFORM obj = new ADMINFORM();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        ADMINHUB obj = new ADMINHUB();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        String search = jTextField1.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    DefaultTableModel tablemodel = (DefaultTableModel)jTable1.getModel();
    tablemodel.setRowCount(0);
    ArrayList<String> data = new ArrayList<>();
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/accounts","root","");
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM user WHERE gradelevel = 'GRADE 12' ");
        while(rs.next()){
            String id = String.valueOf(rs.getInt(1));
            String username = rs.getString(2);
            String password = rs.getString(3);
            String lastName = rs.getString(4);
            String firstName = rs.getString(5);
            String trackStrand = rs.getString(7);
            String schoolType = rs.getString(8);
            
            String tabledata[] = { id, username, password, lastName, firstName, trackStrand, schoolType};
            tablemodel.addRow(tabledata);
        
        }
        con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel tablemodel = (DefaultTableModel) jTable1.getModel();
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
        if(jTable1.getSelectedRowCount()==1)
        {
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/accounts","root","");
        Statement st = con.createStatement();
        String sql = "DELETE FROM user WHERE id = ?";
        int selectedRow = jTable1.getSelectedRow();
        String id = (String)jTable1.getValueAt(selectedRow, 0); 
        int idInt = Integer.parseInt(id);
        PreparedStatement insertStatement = con.prepareStatement(sql);
        insertStatement.setInt(1, idInt);  
        int k = insertStatement.executeUpdate();
        
        if(k==1){
            JOptionPane.showMessageDialog(this, "You have successfully deleted an account");
            tablemodel.removeRow(jTable1.getSelectedRow());
        }
        con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        }
        else if (jTable1.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(this, "Table is empty");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row for deletion");
        }
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel tablemodel = (DefaultTableModel) jTable1.getModel();
        ADMINEDIT editForm = new ADMINEDIT();
        if(jTable1.getSelectedRowCount()==1)
        {
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/accounts","root","");
        Statement st = con.createStatement();
        int selectedRow = jTable1.getSelectedRow();
        String id = (String)jTable1.getValueAt(selectedRow, 0);
        String sql = "SELECT * FROM user WHERE id='"+id+"'";
        ResultSet rs = st.executeQuery(sql);
        if(rs.next()){
            dispose();
            editForm.setVisible(true);
                String studentId = rs.getString(1);
                String username = rs.getString(2);
                String password = rs.getString(3);
                String lastName = rs.getString(4);
                String firstName = rs.getString(5);
                String middleName = rs.getString(6);
                String trackStrand = rs.getString(7);
                String schoolType = rs.getString(8);
                String voucherStatus = rs.getString(9);
                String previousSchool = rs.getString(10);
                String yearGraduated  = rs.getString(11);
                String gradeLevel = rs.getString(12);
                editForm.adminStudentId.setText(studentId);
                editForm.adminEditUsername.setText(username);
                editForm.adminEditPassword.setText(password);
                editForm.adminEditLastName.setText(lastName);
                editForm.adminEditFirstName.setText(firstName);
                editForm.adminEditMiddleName.setText(middleName);
                editForm.adminEditPreviousSchool.setText(previousSchool);
            if(schoolType.equals("PRIVATE")) {
                editForm.adminEditSchoolTypePrivate.doClick();
            } else if (schoolType.equals("PUBLIC")) {
                editForm.adminEditSchoolTypePublic.doClick();
            }
            if(voucherStatus.equals("NON-ESC GUARANTEE")) {
                editForm.adminEditVoucher1.doClick();
            } else if (voucherStatus.equals("NOT VOUCHER RECIPIENT")) {
                editForm.adminEditVoucher1.doClick();
            } else if (voucherStatus.equals("ESC GUARANTEE")) {
                editForm.adminEditVoucher2.doClick();
            } else if (voucherStatus.equals("VOUCHER RECIPIENT")) {
                editForm.adminEditVoucher2.doClick();
            }
            if (trackStrand.equals("ABM")) {
                editForm.adminEditTrack.setSelectedItem("ABM");
            } else if (trackStrand.equals("HUMMS")) {
                editForm.adminEditTrack.setSelectedItem("HUMMS");
            } else if (trackStrand.equals("ICT")) {
                editForm.adminEditTrack.setSelectedItem("ICT");
            } else if (trackStrand.equals("STEM")){
                editForm.adminEditTrack.setSelectedItem("STEM");
            }
            if (gradeLevel.equals("GRADE 11")) {
                editForm.adminEditGradeLevel.setSelectedItem("GRADE 11");
            } else if (gradeLevel.equals("GRADE 12")) {
                editForm.adminEditGradeLevel.setSelectedItem("GRADE 12");
            }
            if (yearGraduated.equals("2016")) {
                editForm.adminEditYear.setSelectedItem("2016");
            } else if (yearGraduated.equals("2017")) {
                editForm.adminEditYear.setSelectedItem("2017");
            } else if (yearGraduated.equals("2018")) {
                editForm.adminEditYear.setSelectedItem("2018");
            } else if (yearGraduated.equals("2019")) {
                editForm.adminEditYear.setSelectedItem("2019");
            } else if (yearGraduated.equals("2020")) {
                editForm.adminEditYear.setSelectedItem("2020");
            } else if (yearGraduated.equals("2021")) {
                editForm.adminEditYear.setSelectedItem("2021");
            } else if (yearGraduated.equals("2022")) {
                editForm.adminEditYear.setSelectedItem("2022");
            } else if (yearGraduated.equals("2023")) {
                editForm.adminEditYear.setSelectedItem("2023");
            } else if (yearGraduated.equals("2024")) {
                editForm.adminEditYear.setSelectedItem("2024");
            } else if (yearGraduated.equals("2025")) {
                editForm.adminEditYear.setSelectedItem("2025");
            }
        }
        con.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMINFORM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMINFORM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMINFORM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMINFORM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMINFORM2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
